-- INSERT INTO Product (title, title_search_vector) VALUES
-- ('Test', to_tsvector('french', 'Le meilleur SGBD OpenSource'));


INSERT INTO Product (title, description) VALUES
('iPhone 12', 'Smartphone Apple avec puce A14 Bionic et double caméra'),
('Samsung Galaxy S21', 'Téléphone phare Samsung avec écran AMOLED et triple caméra'),
('MacBook Air', 'Ordinateur portable Apple avec puce M1 et écran Retina'),
('Dell XPS 13', 'Ultrabook avec écran InfinityEdge et performance puissante'),
('Sony WH-1000XM4', 'Casque à réduction de bruit avec qualité sonore supérieure'),
('Apple Watch Series 6', 'Montre intelligente avec suivi de la santé et ECG'),
('Amazon Echo Dot', 'Enceinte intelligente compacte avec assistant vocal Alexa'),
('Bose QuietComfort 35 II', 'Casque sans fil avec réduction de bruit active'),
('PlayStation 5', 'Console de jeu nouvelle génération de Sony avec graphismes immersifs'),
('Xbox Series X', 'Console de jeu puissante de Microsoft avec résolution 4K'),
('Nintendo Switch', 'Console de jeu hybride pour jouer à la maison et en déplacement'),
('Roku Streaming Stick+', 'Appareil de streaming 4K HDR avec télécommande vocale'),
('Fire TV Stick 4K', 'Appareil de streaming Amazon avec support Ultra HD 4K'),
('Google Chromecast', 'Appareil de streaming pour diffuser du téléphone à la TV'),
('JBL Charge 4', 'Enceinte Bluetooth portable avec longue durée de batterie'),
('Samsung 55-Inch QLED TV', 'TV intelligente avec technologie Quantum Dot et résolution 4K'),
('LG OLED CX Series', 'TV OLED avec noirs parfaits et contraste époustouflant'),
('Sony A8H OLED', 'TV OLED haut de gamme avec qualité d''image exceptionnelle'),
('Canon EOS R5', 'Appareil photo sans miroir avec capteur 45MP et vidéo 8K'),
('Nikon Z6 II', 'Appareil photo sans miroir polyvalent avec autofocus amélioré'),
('GoPro HERO9 Black', 'Caméra d''action avec vidéo 5K et écran avant'),
('Fitbit Charge 4', 'Traqueur de fitness avec GPS intégré et suivi de la fréquence cardiaque'),
('Garmin Forerunner 945', 'Montre de course avancée avec musique et cartes'),
('Dyson V11 Torque Drive', 'Aspirateur sans fil avec aspiration puissante et écran LCD'),
('iRobot Roomba i7+', 'Aspirateur robot avec système de vidage automatique de la saleté'),
('KitchenAid Stand Mixer', 'Robot pâtissier emblématique avec moteur puissant et accessoires'),
('Instant Pot Duo 7-in-1', 'Autocuiseur multifonction avec 7 modes de cuisson'),
('Ninja Foodi Pressure Cooker', 'Autocuiseur et friteuse à air combinés'),
('Philips Airfryer XXL', 'Grande friteuse à air avec technologie rapide de l''air'),
('Breville Barista Express', 'Machine à espresso avec broyeur intégré et buse vapeur'),
('Sony Bravia X900H', 'TV 4K HDR avec technologie LED complète'),
('HP Spectre x360', 'Ordinateur portable convertible avec écran 4K et support du stylet'),
('Lenovo ThinkPad X1 Carbon', 'Ordinateur portable d''affaires ultra-léger avec fonctionnalités de sécurité robustes'),
('ASUS ROG Zephyrus G14', 'Ordinateur portable de jeu avec écran à taux de rafraîchissement élevé'),
('MSI GS66 Stealth', 'Ordinateur portable de jeu mince avec GPU puissant et refroidissement'),
('Alienware m15 R3', 'Ordinateur portable de jeu haute performance avec éclairage personnalisable'),
('Razer Blade 15', 'Ordinateur portable de jeu premium avec châssis en aluminium élégant'),
('Corsair K95 RGB Platinum', 'Clavier de jeu mécanique avec éclairage RGB personnalisable'),
('Logitech MX Master 3', 'Souris ergonomique avec boutons personnalisables et suivi précis'),
('SteelSeries Arctis 7', 'Casque de jeu sans fil avec audio clair et confortable'),
('HyperX Cloud II', 'Casque de jeu confortable avec son surround virtuel 7.1'),
('Apple AirPods Pro', 'Écouteurs sans fil avec réduction active du bruit'),
('Samsung Galaxy Buds+', 'Écouteurs sans fil avec longue durée de batterie'),
('Sony WF-1000XM3', 'Écouteurs sans fil à réduction de bruit avec excellent son'),
('Anker Soundcore Liberty Air 2', 'Écouteurs sans fil abordables avec une grande qualité sonore'),
('Tile Mate', 'Tracker Bluetooth pour localiser rapidement les objets perdus'),
('Kindle Paperwhite', 'Liseuse avec écran haute résolution et design étanche'),
('Ring Video Doorbell 3', 'Sonnette intelligente avec détection de mouvement et enregistrement vidéo'),
('Nest Learning Thermostat', 'Thermostat intelligent avec auto-programmation et contrôle à distance'),
('Arlo Pro 3', 'Caméra de sécurité sans fil avec vidéo 2K et projecteur'),
('August Smart Lock Pro', 'Serrure intelligente avec entrée sans clé et accès à distance'),
('TP-Link Kasa Smart Plug', 'Prise intelligente pour contrôler les appareils à distance via une application'),
('WeMo Smart Plug', 'Prise intelligente Wi-Fi compatible avec le contrôle vocal'),
('Philips Hue White and Color Ambiance', 'Ampoules intelligentes avec couleur et luminosité réglables'),
('Nanoleaf Light Panels', 'Panneaux LED personnalisables pour un éclairage créatif'),
('Eero Pro 6', 'Système Wi-Fi maillé avec connectivité tri-bande'),
('Netgear Nighthawk AX12', 'Routeur Wi-Fi 6 avec performances à haute vitesse'),
('Asus RT-AX88U', 'Routeur Wi-Fi 6 double bande avec sécurité robuste'),
('TP-Link Archer AX6000', 'Routeur Wi-Fi 6 à haute vitesse avec 8 antennes'),
('Google Nest Wifi', 'Système Wi-Fi maillé avec enceinte intelligente intégrée'),
('Belkin BoostCharge Wireless Charging Stand', 'Support de charge sans fil pour smartphones et accessoires'),
('Anker PowerCore 10000', 'Chargeur portable avec grande capacité et charge rapide'),
('RAVPower Portable Charger', 'Batterie externe compacte avec plusieurs ports de charge'),
('Aukey USB-C Hub', 'Hub USB-C multi-port pour étendre la connectivité'),
('VAVA USB-C Docking Station', 'Station d''accueil avec plusieurs ports et alimentation'),
('Samsung T7 Portable SSD', 'SSD externe rapide avec design robuste'),
('SanDisk Extreme Portable SSD', 'SSD durable avec performances à haute vitesse'),
('Western Digital My Passport', 'Disque dur portable avec grande capacité de stockage'),
('Seagate Backup Plus Slim', 'Disque dur externe mince avec logiciel de sauvegarde facile'),
('G-Technology G-Drive', 'Disque dur externe de qualité professionnelle avec haute performance'),
('Lacie Rugged Mini', 'Disque dur externe robuste avec résistance aux chocs'),
('Yeti Rambler Tumbler', 'Gobelet isolé pour garder les boissons chaudes ou froides'),
('Hydro Flask Water Bottle', 'Bouteille d''eau en acier inoxydable avec excellente isolation'),
('Contigo AUTOSEAL Travel Mug', 'Mug de voyage étanche avec technologie auto-seal'),
('CamelBak Chute Mag Water Bottle', 'Bouteille d''eau durable avec bouchon magnétique'),
('Nalgene Tritan Wide Mouth BPA-Free', 'Bouteille d''eau classique avec large goulot et sans BPA'),
('Stanley Classic Vacuum Bottle', 'Bouteille isolée pour garder les boissons chaudes ou froides'),
('Tervis Tumbler', 'Gobelet à double paroi pour maintenir la température des boissons'),
('Simple Modern Summit Water Bottle', 'Bouteille d''eau en acier inoxydable avec large goulot'),
('Fellow Stagg EKG Electric Kettle', 'Bouilloire électrique de précision avec contrôle de température variable'),
('Bonavita Connoisseur Coffee Maker', 'Cafetière avec contrôle précis de la température'),
('Keurig K-Elite', 'Cafetière à portion unique avec réglage pour café glacé'),
('Nespresso VertuoPlus', 'Machine à espresso à portion unique avec options de capsules variées'),
('DeLonghi Magnifica', 'Machine à espresso automatique avec broyeur intégré'),
('Breville Nespresso Creatista Plus', 'Machine à espresso avec buse vapeur et écran LCD'),
('Mr. Coffee Espresso and Cappuccino Maker', 'Machine à espresso et cappuccino abordable avec mousseur'),
('Jura E8 Automatic Coffee Machine', 'Machine à café automatique haut de gamme avec spécialités variées'),
('Saeco Xelsis Super Automatic Espresso Machine', 'Machine à espresso premium avec écran tactile'),
('Philips 3200 Series Fully Automatic Espresso Machine', 'Machine à espresso conviviale avec mousseur à lait'),
('Theragun Elite', 'Appareil de thérapie percussive pour la récupération musculaire'),
('Hyperice Hypervolt', 'Appareil de massage percussif pour soulagement des tissus profonds'),
('Beats Flex Wireless Earphones', 'Écouteurs sans fil avec oreillettes magnétiques et batterie longue durée'),
('Jaybird Vista 2', 'Écouteurs sans fil avec design étanche'),
('Bose Sport Earbuds', 'Écouteurs de sport sans fil avec ajustement sécurisé'),
('Jabra Elite 75t', 'Écouteurs sans fil compacts avec son personnalisable'),
('iPad Pro', 'Tablette Apple avec puce M1 puissante et écran Liquid Retina'),
('Samsung Galaxy Tab S7', 'Tablette Android avec écran à taux de rafraîchissement élevé'),
('Microsoft Surface Pro 7', 'Ordinateur portable 2-en-1 polyvalent avec clavier détachable'),
('Amazon Fire HD 10', 'Tablette abordable avec Alexa et écran Full HD'),
('Lenovo Tab M10', 'Tablette conviviale pour la famille avec mode enfant et haut-parleurs doubles'),
('Sony Xperia 5 II', 'Smartphone compact avec écran 120Hz et triple caméra'),
('OnePlus 9', 'Smartphone phare avec appareil photo Hasselblad et charge rapide'),
('Google Pixel 5', 'Smartphone Android avec excellent appareil photo et logiciel'),
('Oppo Find X3 Pro', 'Smartphone premium avec écran et appareil photo avancés'),
('Xiaomi Mi 11', 'Smartphone haute performance avec écran AMOLED'),
('Huawei P40 Pro', 'Smartphone avec appareil photo Leica et puissant processeur Kirin'),
('Dell Inspiron 15', 'Ordinateur portable fiable avec grand écran et bonnes performances'),
('Acer Aspire 5', 'Ordinateur portable abordable avec bonnes performances et batterie longue durée'),
('HP Envy x360', 'Ordinateur portable convertible avec écran tactile et support du stylet'),
('Microsoft Surface Laptop 4', 'Ordinateur portable premium avec design élégant et matériel puissant'),
('Asus ZenBook 13', 'Ultrabook compact avec écran OLED et batterie longue durée'),
('Bose 700', 'Casque sans fil avec réduction de bruit adaptive'),
('Sennheiser Momentum 3', 'Casque sans fil avec réduction de bruit active et son haute fidélité'),
('Marshall Major IV', 'Casque sans fil avec son signature et design classique'),
('AKG N700NC M2', 'Casque sans fil avec réduction de bruit et son équilibré'),
('Apple AirPods Max', 'Casque sans fil avec réduction de bruit active et audio spatial'),
('Microsoft Surface Headphones 2', 'Casque sans fil avec contrôle tactile et réduction de bruit'),
('Sony WH-CH710N', 'Casque sans fil avec réduction de bruit et autonomie longue'),
('Beats Solo Pro', 'Casque sans fil avec réduction de bruit et son dynamique'),
('Jabra Elite 85h', 'Casque sans fil avec réduction de bruit et résistance à l''eau'),
('Sennheiser HD 450BT', 'Casque sans fil avec réduction de bruit et audio haute qualité'),
('Beyerdynamic DT 770 Pro', 'Casque filaire de studio avec son précis et confortable'),
('Audio-Technica ATH-M50X', 'Casque filaire de monitoring avec excellente réponse en fréquence'),
('Shure SRH440', 'Casque filaire de studio avec son clair et équilibré'),
('Focal Listen Professional', 'Casque filaire de studio avec confort et son détaillé'),
('AKG K240 Studio', 'Casque filaire de studio avec design semi-ouvert'),
('Pioneer DJ HDJ-X5', 'Casque filaire de DJ avec son puissant et durable'),
('Sennheiser HD 280 Pro', 'Casque filaire de studio avec isolation sonore efficace'),
('Sony MDR-7506', 'Casque filaire de studio avec son détaillé et pliable'),
('Bose SoundLink Around-Ear Wireless Headphones II', 'Casque sans fil avec son immersif et confort'),
('JBL E55BT', 'Casque sans fil avec son puissant et design élégant'),
('Plantronics BackBeat Go 810', 'Casque sans fil avec réduction de bruit et autonomie longue'),
('Skullcandy Crusher Wireless', 'Casque sans fil avec basses réglables et design robuste'),
('Grado SR80e', 'Casque filaire ouvert avec son dynamique et détaillé'),
('Audeze LCD-1', 'Casque filaire ouvert avec son précis et design pliable'),
('HiFiMan Sundara', 'Casque filaire ouvert avec transducteurs planaires'),
('Focal Elear', 'Casque filaire ouvert avec son haut de gamme et confort'),
('Bowers & Wilkins PX7', 'Casque sans fil avec réduction de bruit et son hi-fi'),
('Bang & Olufsen Beoplay H9', 'Casque sans fil avec réduction de bruit et design premium');


UPDATE Product SET title_search_vector = to_tsvector('french', title || ' ' || description);

CREATE INDEX idx_product_title_search_vector ON Product USING GIN (title_search_vector);